# version: "3.9"

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dinesh@0402
      POSTGRES_DB: ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # FastAPI Backend Service
  backend:
    build: ./backend
    container_name: ai-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Dinesh%400402@postgres:5432/ai_db
    networks:
      - app_network

  # React Frontend Service
  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"  # Serve React using Nginx on port 3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
